CREATE TABLE cliente
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpf  VARCHAR(11) NOT NULL,
    nome VARCHAR(45),
    CONSTRAINT pk_cliente PRIMARY KEY (id),
    CONSTRAINT uk_cliente_cpf UNIQUE (cpf)
);

CREATE TABLE veiculo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_veiculo VARCHAR(31)      NOT NULL,
    placa        VARCHAR(8)       NOT NULL,
    marca        VARCHAR(50)      NOT NULL,
    modelo       VARCHAR(50)      NOT NULL,
    ano          INTEGER          NOT NULL,
    diaria       DOUBLE PRECISION NOT NULL,
    valor_bem    DOUBLE PRECISION NOT NULL,
    carga        DOUBLE PRECISION,
    capacidade   DOUBLE PRECISION,
    cilindrada   DOUBLE PRECISION,
    autonomia    DOUBLE PRECISION,
    CONSTRAINT pk_veiculo PRIMARY KEY (id),
    CONSTRAINT uk_veiculo_placa UNIQUE (placa)
);

CREATE TABLE aluguel
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    veiculo_id     BIGINT NOT NULL,
    cliente_id     BIGINT NOT NULL,
    dias           INTEGER NOT NULL,
    data_inicio    TIMESTAMP NOT NULL,
    data_devolucao TIMESTAMP,
    aluguel        DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_aluguel PRIMARY KEY (id),
    CONSTRAINT fk_aluguel_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_aluguel_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculo (id)
);

CREATE TABLE users
(
    id       VARCHAR(255) NOT NULL,
    login    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     SMALLINT NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_login UNIQUE (login)
);